name: Build IslaAndroid APK

on:
  # Esto permite ejecutar el workflow manualmente desde la pestaña "Actions"
  workflow_dispatch:

jobs:
  build:
    # Ejecutar en el último Ubuntu disponible
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Descargar el código del repositorio
      - name: Checkout Repository
        # Usa una versión reciente de la acción de checkout
        uses: actions/checkout@v4

      # Paso 2: Configurar el entorno Java (JDK)
      - name: Set up JDK 17
        # Usa una versión reciente de la acción de setup-java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Una distribución de OpenJDK
          java-version: '17'     # La versión de Java que necesitas

      # Paso 3: Dar permisos de ejecución al script gradlew
      # El script gradlew está en la raíz del repositorio después del checkout
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # Paso 4: Compilar el APK de depuración
      # Ejecuta las tareas clean y assembleDebug usando el wrapper de Gradle
      # Esto se ejecuta desde la raíz del repositorio
      - name: Build Debug APK
        run: ./gradlew clean assembleDebug

      # Paso 5: Subir el APK generado como un artefacto del workflow
      # La ruta al APK de depuración es estándar dentro del proyecto Android
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: IslaAndroid-Debug-APK # Nombre con el que se guardará el artefacto
          path: app/build/outputs/apk/debug/app-debug.apk # Ruta al archivo APK
          # Opcional: Define cuánto tiempo quieres que el artefacto esté disponible
          retention-days: 5 # Por ejemplo, 5 días
